
const VIDEO_URLS = [
  "https://storage.googleapis.com/exercise-videos-fit/1 or 2 foot supported chin up isometric.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/1 or 2 foot supported pull up isometric isometric.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/2kb clean.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/2kb reverse lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/2kb row to clean to front squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/2kb single leg rdl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/2kb sumo deadlift.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/3 direction box jumps.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/3 hurdles 3 mt climbers.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/3 point bridge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/Good mornings.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/ab wheel roll out.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/accordian situps.mov",
  "https://storage.googleapis.com/exercise-videos-fit/active push-pull straight leg raise.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/air squat - fast.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/air squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/alternating dumbbell curls.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/alternating dumbbell press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/alternating hand kettlebell swing.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/alternating kettlebell swing.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/alternating runners pose.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/american kb swing.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/arms straight overhead situp.mov",
  "https://storage.googleapis.com/exercise-videos-fit/arnold press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/b stance db rdl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/back rack reverse lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/back squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/ball hamstring curl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/ball knee tucks.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/ball pass.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/ball pushup.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/ball slams.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/band assist pull up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/band assisted dips.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/band assisted pull up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/band lateral raises.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/banded bb dl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/banded bent over row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/banded bicycles.mov",
  "https://storage.googleapis.com/exercise-videos-fit/banded bilateral bent over row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/banded clamshell.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/banded double arm row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/banded glute bridge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/banded high low row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/banded monster walk.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/banded pull apart.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/banded pull through.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/banded reverse lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/banded side steps.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/banded tricep extension.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell assisted pull up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell assisted push up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell bench press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell bent over row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell box squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell burpee deadlift.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell deadlift.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell floor press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell hang power clean.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell hip thrusts.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell incline bench press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell power clean.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell pull up negatives.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell rdl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell rotations.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell seated ohp (z press).mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell skull-crusher.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell sumo deadlift high pull.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/barbell sumo deadlift.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/bb glute bridge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/bear crawl high hips.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/bear crawl, low hips.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/bench curtsy step overs.mov",
  "https://storage.googleapis.com/exercise-videos-fit/bench jump overs.mov",
  "https://storage.googleapis.com/exercise-videos-fit/bent over row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/bicycle crunch - straight leg.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/bicyclecrunch.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/birddog.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/bodyweight dips.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/bosu ball pop squats.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/bosu ball side to side.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/bottom squat hold.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/bottoms up kb press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/box jump - step down.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/box jump single leg land.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/box squat jumps.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/box squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/box toe taps.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/boxer sit up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/broad jump consecutive.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/broad jump.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/bulgarian split jumps.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/bulgarian split squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/burpee box jump over.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/burpee hurdle jump overs.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/burpee.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/butterfly sit-ups.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/cable chest fly.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/chin ups.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/cossack squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/countermovement rotation sling toss.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/crab walk.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/cross legged modified ninja roll.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/curtsy lunges.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/db american swing.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/db curls to rotation.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/db diagonal snatch.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/db front squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/db hammer curl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/db isometric split squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/db lateral raise.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/db overhead tricep extension.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/db power clean & push press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/db reverse fly.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/db single leg hip thrust.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/db skullcrusher.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/db swing.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/db thruster.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dbbentoverfly.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dead stop barbell row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/deadbug (with resistance).mp4",
  "https://storage.googleapis.com/exercise-videos-fit/deadbug.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/decline russian twist.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/decline sit-up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/defecit kettlebell rdl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/deficit jumping lunges.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/devils press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dips.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dive bomber.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/drop to plyo box jump.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell bench press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell bench suppored delt row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell bicep curl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell chest flys.mov",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell curl press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell floor press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell floor skull crusher.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell forward push back lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell front to lateral raise.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell hammer curl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell lunge to step with press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell overhead reverse lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell power clean.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell push press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell rdl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell single arm row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell strict press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/dumbbell upright row to full circle.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/eccentric pullup.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/eccentric pushups.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/elevated forward alternating lunges.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/elevated push-ups.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/engine starter.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/ez bar curl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/face-forward sling toss.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/face-pulls.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/farmers carry double arm.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/farmers carry march in place.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/farmers carry walking lunges.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/farmers lunge to step.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/farmers carry walking lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/feet-knee together deep squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/figure 8 kb clean.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/floating conventional deadlift.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/floor press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/forward alternating push back lunges.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/forward deceleration lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/forward hurdle hops.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/forward lunge with rotation.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/forward push back lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/front foot elevated split squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/front rack reverse lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/front squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/goblet bulgarian split squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/goblet get-up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/goblet pendulum lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/gobletsquat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/golblet deficit lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/gorilla kettlebell row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/half burpee.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/half knee palloff press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/half kneeling bottoms up kb press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/half kneeling dumbbell press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/half kneeling to single arm chest pass.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hand & knee supported chainsaw row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hand release push-ups.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hands elevated push up to box jump.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hanging knee raise.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hanging leg raise.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/heavy wall ball for height.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/heel elevated db squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/heels elevated air squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/heels elevated front squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/heels elevated goblet squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hindu squats.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hip thrusters.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hollow arms down double leg lowers.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hollow arms down single leg lowers.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hollow arms up double leg lowers.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hollow arms up single leg lowers.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hollow flutter kicks.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hollow hang to superman.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hollow hang.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hollow high plank alternating knee to elbow.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hollow high plank alternating leg raise.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hollow hold - high plank.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hollow hold 1.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hollow hold 2.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hollow pushups.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hollow to arch.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hurdle forward back hops.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hurdle lateral hops.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hurdle mini laterals.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/hurdle step overs.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/inchworm into worlds greatest stretch.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/incline chest supported db row (1).mp4",
  "https://storage.googleapis.com/exercise-videos-fit/incline db bench press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/inverted row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/isolation hold pull up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/jump rope.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/jump squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/jumping back squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/jumping ball slam.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/jumping lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/jumping pull-ups.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kb burpee deadlift.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kb front rack squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kb half turkish get up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kb high pulls.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kb romanian deadlift.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kb sa clean & press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kb single legrdl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kb sl rdl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kb swing singles.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kb swinging high pull.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kb thruster.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kettlebell burpee deadlift.mov",
  "https://storage.googleapis.com/exercise-videos-fit/kettlebell deadlift.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kettlebell hang power snatch.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kettlebell hang snatch.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kettlebell lunge weave.mov",
  "https://storage.googleapis.com/exercise-videos-fit/kettlebell power snatch.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kick out kickups.mov",
  "https://storage.googleapis.com/exercise-videos-fit/kickback.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kipling toes to bar.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/knee to elbow plank.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kneeling arm sweep.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/kneeling chest opener.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/knees to elbows.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/landmine alternating arm thruster.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/landmine barbell rotations.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/landmine bent over row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/landmine front squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/landmine hack squat.mov",
  "https://storage.googleapis.com/exercise-videos-fit/landmine incline chest press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/landmine power clean and jerk.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/landmine power clean.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/landmine push press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/landmine single arm row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/landmine single leg rdl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/landmine skater lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/landmine strict press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/landmine thruster.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/lat pulldown.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/lateral bar burpees.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/lateral jumping squats.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/lateral leap.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/lateral lunge into reach.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/lateral lunge to curtsy lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/lateral lunge with t-spine rotation.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/lateral lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/lateral push back lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/lateral push back lunges.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/leg curl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/leg extension.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/leg press calf raise.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/leg press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/loaded cossack squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/loaded squat jumps.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/long sitting shoulder press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/low bar back squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/low plank banded row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/low to high band chops.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/lunge + palloff press hold.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/lungester.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/machine chest fly.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/machine overhead press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/manmakers.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/med ball butterfly sit up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/med ball front squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/med ball hollow plank.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/med ball plank knee to elbow.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/med ball plank with alternating hip extension.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/med ball push ups.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/med ball push-up with knee to elbow hold.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/med ball single arm pass.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/med ball slam into pass.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/med ball thruster.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/medball squat clean.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/medicine ball rolling push-up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/mountain climbers.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/mountain sliders.mov",
  "https://storage.googleapis.com/exercise-videos-fit/nordic curls.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/overhead plate lunge to step.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/overhead plate reverse lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/overhead plate walking lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/overhead squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/overhead trap bar reverse lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/overhead walking plate lunges.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/overhead walking plates lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/pallof press - inside hand emphasis.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/pallof press - outside hand.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/pendulum lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/plank flag pose.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/plank kb lateral pulls.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/plank knee to elbow.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/plank, 3pt to 2pt.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/plank, shoulder taps.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/plate front squat to rotating overhead press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/plate ground to overhead.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/plate hops.mov",
  "https://storage.googleapis.com/exercise-videos-fit/plate overhead carry.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/plate pop squats.mov",
  "https://storage.googleapis.com/exercise-videos-fit/plate row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/plate sit up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/plate stack lateral shuffle.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/plate stack fast step up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/plate stationary side lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/plate thruster.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/plyo push up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/power clean to push press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/power step up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/prone to squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/pull-ups neutral grip.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/punishers.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/push press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/push up shoulder tap.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/push up to ankle tap.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/push up to renegade row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/quadruped kickbacks.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/rainbow slam 20.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/rainbow slam.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/rainbowslam.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/raised quadruped hold.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/rear delt fly.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/recumbent bike.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/renegade row and press.mov",
  "https://storage.googleapis.com/exercise-videos-fit/renegade row and stand.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/renegade row with push-up and stand.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/renegade row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/reverse lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/reverse nordic curls.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/reverse plank.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/rope climbers.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/row and reach in bridge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/russian twists.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/seated banded lat pull.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/seated curl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/seated knee extensions.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/seated reverse flys.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/shoulder punch outs.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/shuttle run.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/side kick through.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/side plank dips, forearm-hand.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/side plank.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/sidekick.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/single arm chest press on box.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/single arm db snatch.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/single arm farmers carry.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/single arm farmers march.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/single arm floor press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/single arm kettlebell reverse lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/single arm overhead reverse lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/single arm row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/single arm thrusters.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/single leg box squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/single leg forward hurdle hops.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/single leg glute bridge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/single leg rdl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/sit up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/skater jumps.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/ski erg.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/skier squat.mov",
  "https://storage.googleapis.com/exercise-videos-fit/skierg crossovers.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/sl high box step ups.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/slam ball alt side lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/slam ball axe chop.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/slam ball burpee.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/slam ball shoulder toss.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/slam ball situps.mov",
  "https://storage.googleapis.com/exercise-videos-fit/slider burpees.mov",
  "https://storage.googleapis.com/exercise-videos-fit/slider frogs inside to outside.mov",
  "https://storage.googleapis.com/exercise-videos-fit/slider frogs outside to inside.mov",
  "https://storage.googleapis.com/exercise-videos-fit/spiderman push up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/squat into thoracic rotation.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/squat rotations.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/squat weave.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/stairmaster.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/standing clamshell.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/starfish plank.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/stationary lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/step-up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/stepback lunge with rotation.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/strict press into push press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/strict press.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/sumo barbell deadlift.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/sumo deadlift high pull.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/sumo squat jumps.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/supermans.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/supinated barbell row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/supine medball chest pass.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/supine straight leg hip lift.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/swimmer back extensions.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/toes to bar.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/trap bar deadlift.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/trap bar farmers carry.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/trap bar jumps.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/treadmill jog.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/treadmill sprint.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/treadmill walk.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/triangle stance rotations.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/tricep bar pushdown.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/tricep kickbacks.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/tricep rope pushdown.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/trx ab roll out.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/trx assisted squat jump.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/trx backstep lunge.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/trx face-pull.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/trx knee tuck.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/trx overhead squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/trx pendulum swings.mov",
  "https://storage.googleapis.com/exercise-videos-fit/trx pistol squats.mov",
  "https://storage.googleapis.com/exercise-videos-fit/trx row with squat.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/trx single arm squat, row, & rotation.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/tuck jumps.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/up down plank.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/upright row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/v up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/wall ball shots.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/wall crawl.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/wall sit bus drivers.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/wall sit.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/weighted accordian situp.mov",
  "https://storage.googleapis.com/exercise-videos-fit/weighted dips.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/weighted pull-ups.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/weighted step-up.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/wide seated cable row.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/wide stance air squat to calf raise.mp4",
  "https://storage.googleapis.com/exercise-videos-fit/z press.mp4"
];

const duplicates = VIDEO_URLS.filter((item, index) => VIDEO_URLS.indexOf(item) !== index);
console.log(JSON.stringify(duplicates, null, 2));
